# Generated by Django 4.2.30 on 2026-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                (
                    "firstName",
                    models.CharField(blank=True, max_length=30, verbose_name="Nome"),
                ),
                (
                    "lastName",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Sobrenome"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não dizer"),
                        ],
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=15)),
            ],
        ),
    ]
