# Generated by Django 6.0.6 on 2026-06-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySongProfileAppBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songlist_1', to='MySongProfileAppBack.song')),
                ('song2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songlist_2', to='MySongProfileAppBack.song')),
                ('song3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songlist_3', to='MySongProfileAppBack.song')),
                ('song4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songlist_4', to='MySongProfileAppBack.song')),
                ('song5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songlist_5', to='MySongProfileAppBack.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='songlist', to='MySongProfileAppBack.user')),
            ],
        ),
    ]
